name = "stealth-proxy"
main = "src/index.js"
type = "javascript"
compatibility_date = "2024-12-16"
send_metrics = false

[env.development]
name = "stealth-proxy-dev"

[env.production]
name = "stealth-proxy-prod"

# Uncomment and update these for custom domain deployment:
# routes = [
#   { pattern = "*/*", zone_name = "yourdomain.com" }
# ]
